name: COOPERBOT-CICD

on: push

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      
      - name: Build&Push
        env:
          APP: "cooperbot"
          REGISTRY: ${{ secrets.GHCR_USERNAME }}
        run: make image push
      
      - name: Test
        run: make test

  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Helm Test
        run: helm lint cooperbot-helm
      
      - name: Helm Package
        run: helm package cooperbot-helm

      - name: Make releases
        with:
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
        run:
          gh release create
          gh release upload v1.0.5 cooperbot-1.0.5.tgz

      - name: Deployment
        run: 
          helm install cooperbot cooperbot-1.0.5.tgz